In [2]:
import tensorflow as tf
print(tf.__version__)
import numpy as np

1.7.0


In [3]:
a = tf.constant(2)
b = tf.constant(3)

In [5]:
c = a + b

In [6]:
print(c)

Tensor("add_1:0", shape=(), dtype=int32)


In [6]:
print(a + b)

Tensor("add_1:0", shape=(), dtype=int32)


In [7]:
with tf.Session() as sess:
    result = sess.run(c)

In [8]:
print(result)

5


In [10]:
const = tf.constant(8)
fillmat = tf.fill((5, 5), 8)
zerosmat = tf.zeros((5, 5))
onesmat = tf.ones((5, 5))
normmat = tf.random_normal((5, 5), mean=0, stddev=1)
unimat = tf.random_uniform((5, 5), minval=0, maxval=1)

In [11]:
ops = [const, fillmat, zerosmat, onesmat, normmat, unimat]

In [12]:
sess = tf.InteractiveSession()

In [15]:
for op in ops:
    print(sess.run(op))
    print()

8

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[-0.15779276  0.44003478 -0.5978629  -0.14995484 -2.357497  ]
 [ 0.01824072 -0.6355437   0.21751443  0.9158157   0.5250855 ]
 [ 0.95062274  0.27770218  0.70323163  0.9128062  -0.38643843]
 [-0.30188882  1.5738039   1.6190153   0.70831656  0.83634156]
 [ 0.16956526  0.8508234   0.5213796  -0.29977986  0.14062901]]

[[0.62259877 0.44811296 0.36915755 0.35852206 0.08603573]
 [0.21181893 0.5189221  0.2945336  0.1206882  0.22647381]
 [0.6772926  0.20903695 0.13507545 0.39491355 0.31327116]
 [0.41566372 0.33938527 0.9734299  0.57614255 0.08299851]
 [0.784233   0.15223873 0.5567485  0.22654808 0.08096242]]



In [31]:
a = tf.constant([[5.0, -2.8], [1.9, 8.0]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [32]:
b = tf.constant([[-2.5], [17.3]])
print(b.shape)

(2, 1)


In [33]:
c = tf.matmul(a, b)

In [34]:
sess.run(c)

array([[-60.94],
       [133.65]], dtype=float32)

In [35]:
print(tf.get_default_graph())

In [36]:
g = tf.Graph()

In [37]:
print(g)

In [38]:
g1 = tf.get_default_graph()
g2 = tf.Graph()

In [39]:
print(g1)

In [40]:
print(g2)

In [41]:
with g2.as_default():
    print(g2 is tf.get_default_graph())

True


In [42]:
print(g2 is tf.get_default_graph())

False


In [43]:
t = tf.random_uniform((5, 5), 0, 1)

In [44]:
t

<tf.Tensor 'random_uniform_1:0' shape=(5, 5) dtype=float32>

In [46]:
v = tf.Variable(initial_value=t)

In [47]:
v

<tf.Variable 'Variable_1:0' shape=(5, 5) dtype=float32_ref>

In [48]:
sess.run(v)

FailedPreconditionError: Attempting to use uninitialized value Variable_1
	 [[Node: _retval_Variable_1_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_1)]]

In [54]:
print(sess.run(tf.report_uninitialized_variables()))

[]


In [55]:
# session.run(my_variable.initializer)

In [49]:
init = tf.global_variables_initializer()

In [50]:
sess.run(init)

In [51]:
sess.run(v)

array([[0.3091961 , 0.9143206 , 0.32941842, 0.2307074 , 0.8186083 ],
       [0.9250319 , 0.30697882, 0.88489413, 0.6856257 , 0.0120579 ],
       [0.78538287, 0.6508502 , 0.23738587, 0.3131789 , 0.11136591],
       [0.16205609, 0.30921304, 0.09548974, 0.22173524, 0.51865625],
       [0.36562443, 0.6856154 , 0.8369392 , 0.9991329 , 0.2414782 ]],
      dtype=float32)

In [52]:
ph = tf.placeholder(tf.float32, shape=(None, 5))

In [4]:
rand_a = np.random.uniform(0, 100, (5, 5))
print(rand_a)

print('\n')

rand_b = np.random.uniform(0, 100, (5, 1))
print(rand_b)

[[14.50407339 86.23496597 19.61347657 20.71953695 51.66654786]
 [20.93844176 57.27255704 66.19322545 11.9653077  37.71634544]
 [41.31145772 75.93072683 38.71937716 45.68246408 67.5989095 ]
 [43.5852355   1.52875363 18.18903223 88.21103394 70.67363547]
 [ 1.13217714 12.43080627 15.85461532  5.29457379 52.38036003]]


[[51.24840911]
 [61.37017615]
 [79.54501222]
 [56.52515711]
 [48.29913626]]


In [5]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [6]:
mul_op = tf.matmul(a, b)

In [7]:
with tf.Session() as sess:
    add_result = sess.run(mul_op, feed_dict={a: rand_a, b: rand_b})
    print(add_result)

[[11262.344 ]
 [12351.237 ]
 [15704.139 ]
 [12173.959 ]
 [ 4911.2617]]
