In [1]:
import torch
print(torch.__version__)

0.4.0


# tensors

In [2]:
t = torch.Tensor(2, 3)
print(t)

tensor([[ 0.0000e+00,  1.0842e-19, -2.4115e-21],
        [-4.6577e-10,  2.2335e+08,  2.2369e+08]])


In [3]:
type(t[0][0])

torch.Tensor

In [4]:
print(t.dim())

2


In [5]:
t[0][0] = 1
t[0][1] = 2
t[0][2] = 3
t[1][0] = 4
t[1][1] = 5
t[1][2] = 6
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])


In [6]:
t2 = torch.Tensor(t)
print(t2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])


In [22]:
t3 = torch.IntTensor([[1, 2],[3, 4]])
print(t3)

tensor([[ 1,  2],
        [ 3,  4]], dtype=torch.int32)


In [23]:
import numpy as np
a = np.array([55, 66])
t4 = torch.Tensor(a)
print(t4)

tensor([ 55.,  66.])


In [24]:
t5 = torch.zeros(2, 3)
print(t5)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])


In [25]:
t6 = torch.ones(2, 3)
print(t6)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [26]:
t7 = torch.ones_like(t4)
print(t7)

tensor([ 1.,  1.])


In [27]:
t1 = torch.ones(2, 2)
t2 = torch.ones(2, 2)
t = t1 + t2
print(t)

tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [28]:
t = t1.add(t2)
print(t)
print(t1)

tensor([[ 2.,  2.],
        [ 2.,  2.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [29]:
t1.add_(t2)
print(t1)

tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [30]:
t1.cos()

tensor([[-0.4161, -0.4161],
        [-0.4161, -0.4161]])

In [31]:
torch.cos(t1)

tensor([[-0.4161, -0.4161],
        [-0.4161, -0.4161]])

In [32]:
torch.linspace(3, 10, steps=5)

tensor([  3.0000,   4.7500,   6.5000,   8.2500,  10.0000])

In [33]:
torch.arange(0, 5)

tensor([ 0.,  1.,  2.,  3.,  4.])

In [34]:
torch.rand((2,3))

tensor([[ 0.5025,  0.6003,  0.9656],
        [ 0.2484,  0.9529,  0.5793]])

In [35]:
a = torch.rand((2, 3))
b = torch.rand((3, 2))

torch.mm(a, b)

tensor([[ 0.7765,  0.4623],
        [ 0.6225,  0.3067]])

In [36]:
n = np.array([2, 3])
t = torch.from_numpy(n)
print(n)
print(t)

[2 3]
tensor([ 2,  3])


In [37]:
n[0] = 100
print(t)

tensor([ 100,    3])


In [38]:
t = torch.FloatTensor([5, 6])
n = t.numpy()
print(t)
print(n)

tensor([ 5.,  6.])
[5. 6.]


In [39]:
t[0] = 100
print(n)

[100.   6.]


# variables

In [40]:
from torch.autograd import Variable

In [ ]:
x = Variable(torch.FloatTensor([11.2]), requires_grad=True)
y = 2 * x

In [ ]:
print(x.data)
print(y.data)

In [ ]:
y.backward()

In [ ]:
print(x.grad)